// Generated by build.mjs: the HubSpot entry point for this card.
import React from 'react';
import { hubspot } from '@hubspot/ui-extensions';
import { CaseEvidenceCard } from './CaseEvidenceCard.tsx';

hubspot.extend<'crm.record.tab'>(({ context }) => <CaseEvidenceCard run={(name, options) => hubspot.serverless(name, options)} actor={context.user.email} />);
