// Generate one deployable HubSpot project per business (projects/<tenant>) from the shared cards, functions and
// apps.mjs. `node build.mjs --check` rebuilds into a temporary folder and fails if the committed projects differ,
// which is the CI gate that keeps what is deployed identical to what is tested.
//
// Per project: hsproject.json (platform 2026.09); src/app/app-hsmeta.json (a private static-auth app with only the
// scopes its parts use); cards with their shared modules copied beside them; each function bundled with esbuild
// into one CommonJS file (app functions load `exports.main`); workflow actions and webhooks pointing at the
// function endpoints (a public app function is served at https://<portal domain>/_hcms/api/<path>); and
// src/hsprofile.live.json, whose account ID and endpoint base URL come from
// ../evidence/<tenant>/deploy.json once a portal exists.
import { build } from 'esbuild';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync }
  from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { APPS } from './apps.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const PLATFORM_VERSION = '2026.09';
const UI_EXTENSIONS = '0.17.0';
const REACT = '18.3.1';

const json = (value) => `${JSON.stringify(value, null, 2)}\n`;
const write = (path, text) => {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text.replace(/\r\n/g, '\n'));
};

// ------------------------------------------------------------------ typology catalogue for the AML card
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < text.length; i += 1) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i += 1; } else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; } else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; } else if (c !== '\r') field += c;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  const [header, ...body] = rows;
  return body.map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ''])));
}

function typologies() {
  const rows = parseCsv(readFileSync(join(ROOT, 'data/snapshots/aml/typologies.csv'), 'utf8'));
  const entries = Object.fromEntries(rows.map((r) => [r.typology_id, {
    rule: r.rule_code, hypothesis: r.hypothesis, lawfulLookalike: r.lawful_lookalike, discriminator: r.discriminator,
    limitation: r.known_limitation, minimumEvidence: r.minimum_evidence,
  }]));
  return '// Generated by build.mjs from data/snapshots/aml/typologies.csv (the AML project\'s typology evidence\n'
    + '// catalogue). Do not edit.\n'
    + 'export type Typology = { rule: string; hypothesis: string; lawfulLookalike: string; discriminator: string;\n'
    + '  limitation: string; minimumEvidence: string };\n'
    + `export const TYPOLOGIES: Record<string, Typology> = ${JSON.stringify(entries, null, 2)};\n`;
}

// ------------------------------------------------------------------ one project
function deployment(tenant) {
  const path = join(ROOT, 'evidence', tenant, 'deploy.json');
  const found = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : {};
  return { accountId: found.accountId ?? 0, endpointBaseUrl: found.endpointBaseUrl ?? 'https://example.invalid' };
}

function entry(card) {
  const props = [];
  if (card.needs.includes('run')) props.push('run={(name, options) => hubspot.serverless(name, options)}');
  if (card.needs.includes('portalId')) props.push('portalId={context.portal.id}');
  const args = card.needs.includes('portalId') ? '({ context })' : '()';
  return [
    '// Generated by build.mjs: the HubSpot entry point for this card.',
    "import React from 'react';",
    "import { hubspot } from '@hubspot/ui-extensions';",
    `import { ${card.component} } from './${card.component}.tsx';`,
    '',
    `hubspot.extend<'crm.record.tab'>(${args} => <${card.component}${props.length ? ` ${props.join(' ')}` : ''} />);`,
    '',
  ].join('\n');
}

function copyShared(target, cardCode) {
  const used = new Set([...cardCode.matchAll(/from '\.\/shared\/([\w-]+\.js)'/g)].map((m) => m[1]));
  for (const file of [...used].sort()) write(join(target, file), readFileSync(join(HERE, 'shared', file), 'utf8'));
}

async function bundle(source, outfile) {
  const result = await build({ entryPoints: [source], bundle: true, platform: 'node', format: 'cjs',
    target: 'node20', write: false, legalComments: 'none', logLevel: 'silent' });
  write(outfile, `// Generated by build.mjs from hubspot/functions/${relative(join(HERE, 'functions'), source)
    .replace(/\\/g, '/')} and hubspot/shared. Do not edit.\n${result.outputFiles[0].text}`);
}

async function project(tenant, app, out) {
  const src = join(out, 'src');
  const deploy = deployment(tenant);
  write(join(out, 'hsproject.json'), json({ name: `crm-platform-${tenant}`, srcDir: 'src',
    platformVersion: PLATFORM_VERSION }));
  write(join(src, 'hsprofile.live.json'), json({ accountId: deploy.accountId,
    variables: { ENDPOINT_BASE_URL: deploy.endpointBaseUrl } }));
  write(join(src, 'app', 'app-hsmeta.json'), json({ uid: `crm_platform_${tenant}`, type: 'app', config: {
    name: app.name, description: app.description, distribution: 'private',
    auth: { type: 'static', requiredScopes: app.scopes, optionalScopes: [] },
    permittedUrls: { fetch: [], iframe: [], img: [] },
    support: { documentationUrl: 'https://github.com/KushPatel29/hubspot-crm-platform' },
  } }));

  const cards = join(src, 'app', 'cards');
  write(join(cards, 'package.json'), json({ name: `crm-platform-${tenant}-cards`, version: '1.0.0', private: true,
    type: 'module', dependencies: { '@hubspot/ui-extensions': UI_EXTENSIONS, react: REACT } }));
  write(join(cards, 'tsconfig.json'), readFileSync(join(HERE, 'cards', 'tsconfig.project.json'), 'utf8'));
  write(join(cards, 'format.ts'), readFileSync(join(HERE, 'cards', 'format.ts'), 'utf8'));
  if (app.cards.some((c) => c.component === 'CaseEvidenceCard')) {
    write(join(cards, 'generated', 'typologies.ts'), typologies());
  }
  for (const card of app.cards) {
    const code = readFileSync(join(HERE, 'cards', `${card.component}.tsx`), 'utf8').replaceAll("'../shared/", "'./shared/");
    write(join(cards, `${card.component}.tsx`), code);
    copyShared(join(cards, 'shared'), code);
    write(join(cards, `${card.component}Entry.tsx`), entry(card));
    write(join(cards, `${card.uid}-hsmeta.json`), json({ uid: card.uid, type: 'card', config: {
      name: card.name, description: card.description, location: 'crm.record.tab',
      entrypoint: `/app/cards/${card.component}Entry.tsx`, objectTypes: card.objectTypes,
    } }));
  }

  const functions = join(src, 'app', 'functions');
  write(join(functions, 'package.json'), json({ name: `crm-platform-${tenant}-functions`, version: '1.0.0',
    private: true, dependencies: {} }));
  for (const fn of app.functions) {
    await bundle(join(HERE, 'functions', `${fn.name}.js`), join(functions, `${fn.name}.js`));
    const config = { entrypoint: `/app/functions/${fn.name}.js`, secretKeys: fn.secrets ?? [] };
    if (fn.endpoint) config.endpoint = { path: fn.endpoint, methods: ['POST'] };
    write(join(functions, `${fn.name}-hsmeta.json`), json({ uid: fn.name, type: 'app-function', config }));
  }

  for (const action of app.workflowActions ?? []) {
    const fn = app.functions.find((f) => f.name === action.function);
    write(join(src, 'app', 'workflow-actions', `${action.uid}-hsmeta.json`), json({ uid: action.uid,
      type: 'workflow-action', config: {
        actionUrl: `\${ENDPOINT_BASE_URL}/_hcms/api/${fn.endpoint}`, isPublished: true,
        supportedClients: [{ client: 'WORKFLOWS' }], inputFields: action.inputFields,
        outputFields: action.outputFields, labels: { en: action.labels }, objectTypes: action.objectTypes,
      } }));
  }
  if (app.webhooks) {
    const fn = app.functions.find((f) => f.name === app.webhooks.function);
    write(join(src, 'app', 'webhooks', 'webhooks-hsmeta.json'), json({ uid: 'webhooks', type: 'webhooks', config: {
      settings: { targetUrl: `\${ENDPOINT_BASE_URL}/_hcms/api/${fn.endpoint}`, maxConcurrentRequests: 10 },
      subscriptions: {
        crmObjects: app.webhooks.crmObjects.map((s) => ({ ...s, active: true })),
        hubEvents: app.webhooks.hubEvents.map((s) => ({ ...s, active: true })),
      },
    } }));
  }
}

// ------------------------------------------------------------------ all projects, or a check
function files(dir, base = dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? files(path, base) : [relative(base, path).replace(/\\/g, '/')];
  });
}

async function buildAll(out) {
  for (const [tenant, app] of Object.entries(APPS)) await project(tenant, app, join(out, tenant));
}

const check = process.argv.includes('--check');
write(join(HERE, 'cards', 'generated', 'typologies.ts'), typologies());
if (check) {
  const temp = mkdtempSync(join(tmpdir(), 'crm-platform-'));
  await buildAll(temp);
  const committed = join(HERE, 'projects');
  const all = new Set([...files(temp), ...files(committed)]);
  const stale = [...all].filter((f) => !existsSync(join(temp, f)) || !existsSync(join(committed, f))
    || readFileSync(join(temp, f), 'utf8') !== readFileSync(join(committed, f), 'utf8'));
  rmSync(temp, { recursive: true, force: true });
  if (stale.length) {
    console.error(`Generated HubSpot projects are stale (run npm run build):\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('HubSpot projects match their sources');
} else {
  const out = join(HERE, 'projects');
  // Empty each project folder rather than deleting it: on Windows a folder that is some shell's working directory
  // cannot be removed, and a deploy is usually run from inside one.
  for (const tenant of existsSync(out) ? readdirSync(out) : []) {
    for (const entry of readdirSync(join(out, tenant))) rmSync(join(out, tenant, entry), { recursive: true, force: true });
    if (!(tenant in APPS)) rmSync(join(out, tenant), { recursive: true, force: true });
  }
  await buildAll(out);
  console.log(`built ${Object.keys(APPS).length} HubSpot projects: ${Object.keys(APPS).join(', ')}`);
}
