// Generated by build.mjs: the HubSpot entry point for this card.
import React from 'react';
import { hubspot } from '@hubspot/ui-extensions';
import { RevenueTruthCard } from './RevenueTruthCard.tsx';

hubspot.extend<'crm.record.tab'>(() => <RevenueTruthCard />);
