// Generated by build.mjs from hubspot/functions/deal_margin.js and hubspot/shared. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/deal_margin.js
var deal_margin_exports = {};
__export(deal_margin_exports, {
  LINE_PROPERTIES: () => LINE_PROPERTIES,
  dealLines: () => dealLines,
  main: () => main
});
module.exports = __toCommonJS(deal_margin_exports);

// shared/hubspot-api.js
var HubSpotApiError = class extends Error {
  constructor(status, method, path, category = "", correlationId = "") {
    super(`HubSpot ${method} ${path} failed: HTTP ${status}${category ? ` ${category}` : ""}${correlationId ? ` (correlation ${correlationId})` : ""}`);
    this.status = status;
    this.category = category;
  }
};
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function client({
  token = process.env.PRIVATE_APP_ACCESS_TOKEN,
  fetchImpl = globalThis.fetch,
  wait = sleep,
  base = "https://api.hubapi.com"
} = {}) {
  if (!token) throw new Error("PRIVATE_APP_ACCESS_TOKEN is not available to this function");
  async function request(method, path, body) {
    let status = 0;
    for (let attempt = 0; attempt < 3; attempt += 1) {
      const response = await fetchImpl(base + path, {
        method,
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: body === void 0 ? void 0 : JSON.stringify(body)
      });
      status = response.status;
      if (status === 429 || status >= 500) {
        const retryAfter = Number(response.headers?.get?.("retry-after") ?? 0);
        await wait(Math.min(2e3, Math.max(retryAfter * 1e3, 250 * 2 ** attempt)));
        continue;
      }
      const text = await response.text();
      const payload = text ? JSON.parse(text) : {};
      if (status < 200 || status >= 300) {
        throw new HubSpotApiError(status, method, path.split("?")[0], payload.category, payload.correlationId);
      }
      return payload;
    }
    throw new HubSpotApiError(status, method, path.split("?")[0], "still failing after retries");
  }
  const api = {
    request,
    get: (path) => request("GET", path),
    post: (path, body) => request("POST", path, body),
    patch: (path, body) => request("PATCH", path, body),
    put: (path, body) => request("PUT", path, body),
    // Associated record IDs (v4), following pages.
    async associated(fromType, id, toType) {
      const ids = [];
      let after = "";
      do {
        const page = await request("GET", `/crm/v4/objects/${fromType}/${id}/associations/${toType}?limit=500${after}`);
        for (const row of page.results ?? []) ids.push({ id: String(row.toObjectId), types: row.associationTypes ?? [] });
        const next = page.paging?.next?.after;
        after = next ? `&after=${next}` : "";
      } while (after);
      return ids;
    },
    async batchRead(objectType, ids, properties) {
      const out = [];
      for (let i = 0; i < ids.length; i += 100) {
        const page = await request("POST", `/crm/v3/objects/${objectType}/batch/read`, {
          inputs: ids.slice(i, i + 100).map((id) => ({ id })),
          properties
        });
        out.push(...page.results ?? []);
      }
      return out;
    },
    // A custom object's type ID from its name ("recommendation" -> "2-123456").
    async customType(name) {
      const schemas = await request("GET", "/crm/v3/schemas");
      const schema = (schemas.results ?? []).find((s) => s.name === name);
      if (!schema) throw new Error(`custom object "${name}" is not defined in this portal`);
      return schema.objectTypeId;
    },
    async labelType(fromType, toType, label) {
      const labels = await request("GET", `/crm/v4/associations/${fromType}/${toType}/labels`);
      const match = (labels.results ?? []).find((l) => label ? l.label === label : !l.label);
      if (!match) throw new Error(`no association ${label ? `labelled "${label}"` : "type"} from ${fromType} to ${toType}`);
      return { associationCategory: match.category, associationTypeId: match.typeId };
    }
  };
  return api;
}

// shared/signature.js
var MAX_AGE_MS = 5 * 60 * 1e3;

// shared/endpoint.js
function secret(context, name) {
  return context?.secrets?.[name] || process.env[name] || void 0;
}
function appClient(context) {
  return client({ token: secret(context, "PRIVATE_APP_ACCESS_TOKEN") });
}
function respond(statusCode, body) {
  return { statusCode, body };
}

// shared/guardrail.js
var APPROVAL_TIERS = [
  [0.02, "Rep"],
  [0.05, "Sales manager"],
  [0.1, "Commercial director"],
  [Infinity, "VP Finance"]
];
var APPROVERS = ["None", "Rep", "Sales manager", "Commercial director", "VP Finance"];
var VERDICTS = ["Above stretch", "At target", "Below target", "Below floor", "Loss-making"];
var TOLERANCE = 1e-9;
function band(targetMargin) {
  return { floor: Math.max(0.05, targetMargin - 0.09), target: targetMargin, stretch: targetMargin + 0.08 };
}
function scoreLine(price, cost, quantity, targetMargin) {
  const { floor, target, stretch } = band(targetMargin);
  const revenue = price * quantity;
  const marginPct = price > 0 ? (price - cost) / price : 0;
  let verdict;
  if (marginPct >= stretch - TOLERANCE) verdict = "Above stretch";
  else if (marginPct >= target - TOLERANCE) verdict = "At target";
  else if (marginPct >= floor - TOLERANCE) verdict = "Below target";
  else if (price - cost > 0) verdict = "Below floor";
  else verdict = "Loss-making";
  const gap = target - marginPct;
  let approver = "None";
  if (gap > TOLERANCE) approver = APPROVAL_TIERS.find(([limit]) => gap <= limit)[1];
  return {
    marginPct,
    verdict,
    approver,
    gap,
    gapDollars: Math.max(0, gap) * revenue,
    revenue,
    margin: (price - cost) * quantity,
    floor,
    target,
    stretch
  };
}
function scoreDeal(lines) {
  const scored = lines.map((l) => scoreLine(l.price, l.cost, l.quantity, l.targetMargin));
  if (scored.length === 0) {
    return { blendedMarginPct: 0, verdict: "At target", approver: "None", gapDollars: 0, worstLine: -1, lines: [] };
  }
  const revenue = scored.reduce((sum, s) => sum + s.revenue, 0);
  let worst = 0;
  scored.forEach((s, i) => {
    const w = scored[worst];
    const rank = VERDICTS.indexOf(s.verdict) - VERDICTS.indexOf(w.verdict);
    if (rank > 0 || rank === 0 && s.gap > w.gap) worst = i;
  });
  const approver = scored.reduce(
    (best, s) => APPROVERS.indexOf(s.approver) > APPROVERS.indexOf(best) ? s.approver : best,
    "None"
  );
  return {
    blendedMarginPct: revenue > 0 ? scored.reduce((sum, s) => sum + s.margin, 0) / revenue : 0,
    verdict: scored[worst].verdict,
    approver,
    gapDollars: scored.reduce((sum, s) => sum + s.gapDollars, 0),
    worstLine: worst,
    lines: scored
  };
}

// functions/deal_margin.js
var LINE_PROPERTIES = ["name", "price", "quantity", "hs_cost_of_goods_sold", "hs_product_id"];
async function dealLines(api, dealId) {
  const links = await api.associated("deals", dealId, "line_items");
  const items = await api.batchRead("line_items", links.map((l) => l.id), LINE_PROPERTIES);
  const productIds = [...new Set(items.map((i) => i.properties.hs_product_id).filter(Boolean))];
  const products = await api.batchRead("products", productIds, ["meridian_target_margin", "name"]);
  const targets = Object.fromEntries(products.map((p) => [p.id, Number(p.properties.meridian_target_margin)]));
  const lines = items.map((item) => ({
    id: item.id,
    name: item.properties.name,
    price: Number(item.properties.price),
    cost: Number(item.properties.hs_cost_of_goods_sold),
    quantity: Number(item.properties.quantity),
    targetMargin: targets[item.properties.hs_product_id]
  })).sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id));
  const unscored = lines.filter((l) => !Number.isFinite(l.targetMargin) || !Number.isFinite(l.cost));
  return { lines: lines.filter((l) => !unscored.includes(l)), unscored };
}
async function main(context, { api = appClient(context) } = {}) {
  const dealId = context.propertiesToSend?.hs_object_id ?? context.parameters?.dealId;
  if (!dealId) return respond(400, { ok: false, error: "no deal in context" });
  const { lines, unscored } = await dealLines(api, dealId);
  const score = scoreDeal(lines);
  return respond(200, {
    ok: true,
    basis: "Invoice margin: quoted price less cost of goods. Rebates, freight and terms live in the ERP.",
    deal: {
      blendedMarginPct: score.blendedMarginPct,
      verdict: score.verdict,
      approver: score.approver,
      gapDollars: score.gapDollars,
      worstLine: score.worstLine
    },
    lines: lines.map((line, i) => ({ ...line, ...score.lines[i] })),
    unscored: unscored.map((l) => l.name)
  });
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  LINE_PROPERTIES,
  dealLines,
  main
});
