// Generated by build.mjs: the HubSpot entry point for this card.
import React from 'react';
import { hubspot } from '@hubspot/ui-extensions';
import { DealMarginCard } from './DealMarginCard.tsx';

hubspot.extend<'crm.record.tab'>(() => <DealMarginCard run={(name, options) => hubspot.serverless(name, options)} />);
