// Generated by build.mjs from hubspot/functions/advance_lifecycle.js and hubspot/shared. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/advance_lifecycle.js
var advance_lifecycle_exports = {};
__export(advance_lifecycle_exports, {
  PATH: () => PATH,
  main: () => main
});
module.exports = __toCommonJS(advance_lifecycle_exports);

// shared/hubspot-api.js
var HubSpotApiError = class extends Error {
  constructor(status, method, path, category = "", correlationId = "") {
    super(`HubSpot ${method} ${path} failed: HTTP ${status}${category ? ` ${category}` : ""}${correlationId ? ` (correlation ${correlationId})` : ""}`);
    this.status = status;
    this.category = category;
  }
};
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function client({
  token = process.env.PRIVATE_APP_ACCESS_TOKEN,
  fetchImpl = globalThis.fetch,
  wait = sleep,
  base = "https://api.hubapi.com"
} = {}) {
  if (!token) throw new Error("PRIVATE_APP_ACCESS_TOKEN is not available to this function");
  async function request(method, path, body) {
    let status = 0;
    for (let attempt = 0; attempt < 3; attempt += 1) {
      const response = await fetchImpl(base + path, {
        method,
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: body === void 0 ? void 0 : JSON.stringify(body)
      });
      status = response.status;
      if (status === 429 || status >= 500) {
        const retryAfter = Number(response.headers?.get?.("retry-after") ?? 0);
        await wait(Math.min(2e3, Math.max(retryAfter * 1e3, 250 * 2 ** attempt)));
        continue;
      }
      const text = await response.text();
      const payload = text ? JSON.parse(text) : {};
      if (status < 200 || status >= 300) {
        throw new HubSpotApiError(status, method, path.split("?")[0], payload.category, payload.correlationId);
      }
      return payload;
    }
    throw new HubSpotApiError(status, method, path.split("?")[0], "still failing after retries");
  }
  const api = {
    request,
    get: (path) => request("GET", path),
    post: (path, body) => request("POST", path, body),
    patch: (path, body) => request("PATCH", path, body),
    put: (path, body) => request("PUT", path, body),
    // Associated record IDs (v4), following pages.
    async associated(fromType, id, toType) {
      const ids = [];
      let after = "";
      do {
        const page = await request("GET", `/crm/v4/objects/${fromType}/${id}/associations/${toType}?limit=500${after}`);
        for (const row of page.results ?? []) ids.push({ id: String(row.toObjectId), types: row.associationTypes ?? [] });
        const next = page.paging?.next?.after;
        after = next ? `&after=${next}` : "";
      } while (after);
      return ids;
    },
    async batchRead(objectType, ids, properties) {
      const out = [];
      for (let i = 0; i < ids.length; i += 100) {
        const page = await request("POST", `/crm/v3/objects/${objectType}/batch/read`, {
          inputs: ids.slice(i, i + 100).map((id) => ({ id })),
          properties
        });
        out.push(...page.results ?? []);
      }
      return out;
    },
    // A custom object's type ID from its name ("recommendation" -> "2-123456").
    async customType(name) {
      const schemas = await request("GET", "/crm/v3/schemas");
      const schema = (schemas.results ?? []).find((s) => s.name === name);
      if (!schema) throw new Error(`custom object "${name}" is not defined in this portal`);
      return schema.objectTypeId;
    },
    async labelType(fromType, toType, label) {
      const labels = await request("GET", `/crm/v4/associations/${fromType}/${toType}/labels`);
      const match = (labels.results ?? []).find((l) => label ? l.label === label : !l.label);
      if (!match) throw new Error(`no association ${label ? `labelled "${label}"` : "type"} from ${fromType} to ${toType}`);
      return { associationCategory: match.category, associationTypeId: match.typeId };
    }
  };
  return api;
}

// shared/lifecycle.js
var LADDER = [
  "subscriber",
  "lead",
  "marketingqualifiedlead",
  "salesqualifiedlead",
  "opportunity",
  "customer",
  "evangelist"
];
function decide(current, target) {
  if (!LADDER.includes(target)) {
    return { action: "reject", reason: `"${target}" is not a lifecycle stage this action can set` };
  }
  if (current === "other") {
    return { action: "keep", reason: `the contact is marked "other"; that is a person's decision, not a stage` };
  }
  const from = current ? LADDER.indexOf(current) : -1;
  if (current && from === -1) {
    return { action: "keep", reason: `unknown current stage "${current}"; not changed` };
  }
  const to = LADDER.indexOf(target);
  if (to <= from) {
    return { action: "keep", reason: to === from ? "already at that stage" : "that would move the contact backwards" };
  }
  return { action: "move", reason: `${current || "no stage"} to ${target}` };
}

// shared/signature.js
var import_node_crypto = require("node:crypto");
var MAX_AGE_MS = 5 * 60 * 1e3;
var DECODE = {
  "%3A": ":",
  "%2F": "/",
  "%3F": "?",
  "%40": "@",
  "%21": "!",
  "%24": "$",
  "%27": "'",
  "%28": "(",
  "%29": ")",
  "%2A": "*",
  "%2C": ",",
  "%3B": ";"
};
function canonicalUri(uri) {
  return uri.replace(/%3A|%2F|%3F|%40|%21|%24|%27|%28|%29|%2A|%2C|%3B/gi, (m) => DECODE[m.toUpperCase()]);
}
function sign(secret, method, uri, body, timestamp) {
  return (0, import_node_crypto.createHmac)("sha256", secret).update(`${method.toUpperCase()}${canonicalUri(uri)}${body}${timestamp}`).digest("base64");
}
function verify(secret, { method, uri, body, timestamp, signature }, now) {
  if (!secret) return { ok: false, reason: "no client secret configured" };
  if (!signature || !timestamp) return { ok: false, reason: "unsigned request" };
  const age = now - Number(timestamp);
  if (!Number.isFinite(age) || age > MAX_AGE_MS || age < -MAX_AGE_MS) return { ok: false, reason: "stale timestamp" };
  const expected = Buffer.from(sign(secret, method, uri, body, timestamp));
  const given = Buffer.from(String(signature));
  if (expected.length !== given.length || !(0, import_node_crypto.timingSafeEqual)(expected, given)) {
    return { ok: false, reason: "signature mismatch" };
  }
  return { ok: true };
}
function header(headers, name) {
  const wanted = name.toLowerCase();
  for (const [key, value] of Object.entries(headers ?? {})) {
    if (key.toLowerCase() === wanted) return Array.isArray(value) ? value[0] : value;
  }
  return void 0;
}

// shared/endpoint.js
function rawBody(context) {
  const body = context.body;
  if (body === void 0 || body === null) return "";
  return typeof body === "string" ? body : JSON.stringify(body);
}
function parsedBody(context) {
  const body = context.body;
  if (typeof body === "string") return body ? JSON.parse(body) : {};
  return body ?? {};
}
function signedRequest(context, path, base = process.env.ENDPOINT_BASE_URL) {
  const query = new URLSearchParams(context.query ?? {}).toString();
  return {
    method: context.method ?? "POST",
    uri: `${(base ?? "").replace(/\/$/, "")}${path}${query ? `?${query}` : ""}`,
    body: rawBody(context),
    timestamp: header(context.headers, "x-hubspot-request-timestamp"),
    signature: header(context.headers, "x-hubspot-signature-v3")
  };
}
function authenticate(context, path, { secret = process.env.HUBSPOT_CLIENT_SECRET, now = Date.now() } = {}) {
  return verify(secret, signedRequest(context, path), now);
}
function respond(statusCode, body) {
  return { statusCode, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) };
}

// functions/advance_lifecycle.js
var PATH = "/advance-lifecycle";
async function main(context, { api, now = Date.now(), secret } = {}) {
  const auth = authenticate(context, PATH, { secret, now });
  if (!auth.ok) return respond(401, { error: auth.reason });
  const request = parsedBody(context);
  const contactId = request.object?.objectId;
  const target = request.inputFields?.target_stage;
  if (!contactId || !target) return respond(400, { error: "needs a contact and a target_stage" });
  const hubspot = api ?? client();
  const contact = await hubspot.get(`/crm/v3/objects/contacts/${contactId}?properties=lifecyclestage`);
  const current = contact.properties?.lifecyclestage ?? "";
  const decision = decide(current, target);
  if (decision.action === "move") {
    await hubspot.patch(`/crm/v3/objects/contacts/${contactId}`, { properties: { lifecyclestage: target } });
  }
  return respond(200, { outputFields: {
    outcome: decision.action === "move" ? "moved" : decision.action === "keep" ? "kept" : "rejected",
    from_stage: current || "none",
    reason: decision.reason
  } });
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  PATH,
  main
});
