// Generated by build.mjs from hubspot/functions/webhook_receiver.js and hubspot/shared. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/webhook_receiver.js
var webhook_receiver_exports = {};
__export(webhook_receiver_exports, {
  PATH: () => PATH,
  main: () => main,
  summarise: () => summarise
});
module.exports = __toCommonJS(webhook_receiver_exports);

// shared/signature.js
var import_node_crypto = require("node:crypto");
var MAX_AGE_MS = 5 * 60 * 1e3;
var DECODE = {
  "%3A": ":",
  "%2F": "/",
  "%3F": "?",
  "%40": "@",
  "%21": "!",
  "%24": "$",
  "%27": "'",
  "%28": "(",
  "%29": ")",
  "%2A": "*",
  "%2C": ",",
  "%3B": ";"
};
function canonicalUri(uri) {
  return uri.replace(/%3A|%2F|%3F|%40|%21|%24|%27|%28|%29|%2A|%2C|%3B/gi, (m) => DECODE[m.toUpperCase()]);
}
function sign(secret, method, uri, body, timestamp) {
  return (0, import_node_crypto.createHmac)("sha256", secret).update(`${method.toUpperCase()}${canonicalUri(uri)}${body}${timestamp}`).digest("base64");
}
function verify(secret, { method, uri, body, timestamp, signature }, now) {
  if (!secret) return { ok: false, reason: "no client secret configured" };
  if (!signature || !timestamp) return { ok: false, reason: "unsigned request" };
  const age = now - Number(timestamp);
  if (!Number.isFinite(age) || age > MAX_AGE_MS || age < -MAX_AGE_MS) return { ok: false, reason: "stale timestamp" };
  const expected = Buffer.from(sign(secret, method, uri, body, timestamp));
  const given = Buffer.from(String(signature));
  if (expected.length !== given.length || !(0, import_node_crypto.timingSafeEqual)(expected, given)) {
    return { ok: false, reason: "signature mismatch" };
  }
  return { ok: true };
}
function header(headers, name) {
  const wanted = name.toLowerCase();
  for (const [key, value] of Object.entries(headers ?? {})) {
    if (key.toLowerCase() === wanted) return Array.isArray(value) ? value[0] : value;
  }
  return void 0;
}

// shared/endpoint.js
function rawBody(context) {
  const body = context.body;
  if (body === void 0 || body === null) return "";
  return typeof body === "string" ? body : JSON.stringify(body);
}
function parsedBody(context) {
  const body = context.body;
  if (typeof body === "string") return body ? JSON.parse(body) : {};
  return body ?? {};
}
function signedRequest(context, path, base = process.env.ENDPOINT_BASE_URL) {
  const query = new URLSearchParams(context.query ?? {}).toString();
  return {
    method: context.method ?? "POST",
    uri: `${(base ?? "").replace(/\/$/, "")}${path}${query ? `?${query}` : ""}`,
    body: rawBody(context),
    timestamp: header(context.headers, "x-hubspot-request-timestamp"),
    signature: header(context.headers, "x-hubspot-signature-v3")
  };
}
function authenticate(context, path, { secret = process.env.HUBSPOT_CLIENT_SECRET, now = Date.now() } = {}) {
  return verify(secret, signedRequest(context, path), now);
}
function respond(statusCode, body) {
  return { statusCode, body };
}

// functions/webhook_receiver.js
var PATH = "/hs/serverless/webhooks";
function summarise(events) {
  const byType = {};
  for (const event of events) byType[event.subscriptionType] = (byType[event.subscriptionType] ?? 0) + 1;
  return {
    events: events.length,
    byType,
    eventIds: events.map((e) => e.eventId).slice(0, 20),
    objects: [...new Set(events.map((e) => e.objectId))].slice(0, 20),
    attempts: Math.max(0, ...events.map((e) => Number(e.attemptNumber ?? 0)))
  };
}
async function main(context, { now = Date.now(), secret, log = console.log } = {}) {
  const auth = authenticate(context, PATH, { secret, now });
  if (!auth.ok) {
    log(JSON.stringify({ webhook: "refused", reason: auth.reason }));
    return respond(401, { error: auth.reason });
  }
  const events = parsedBody(context);
  if (!Array.isArray(events)) return respond(400, { error: "expected an array of events" });
  const summary = summarise(events);
  log(JSON.stringify({ webhook: "accepted", ...summary }));
  return respond(200, { accepted: summary.events });
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  PATH,
  main,
  summarise
});
