// Generated by build.mjs from hubspot/functions/case_transition.js and hubspot/shared. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/case_transition.js
var case_transition_exports = {};
__export(case_transition_exports, {
  main: () => main
});
module.exports = __toCommonJS(case_transition_exports);

// shared/hubspot-api.js
var HubSpotApiError = class extends Error {
  constructor(status, method, path, category = "", correlationId = "") {
    super(`HubSpot ${method} ${path} failed: HTTP ${status}${category ? ` ${category}` : ""}${correlationId ? ` (correlation ${correlationId})` : ""}`);
    this.status = status;
    this.category = category;
  }
};
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function client({
  token = process.env.PRIVATE_APP_ACCESS_TOKEN,
  fetchImpl = globalThis.fetch,
  wait = sleep,
  base = "https://api.hubapi.com"
} = {}) {
  if (!token) throw new Error("PRIVATE_APP_ACCESS_TOKEN is not available to this function");
  async function request(method, path, body) {
    let status = 0;
    for (let attempt = 0; attempt < 3; attempt += 1) {
      const response = await fetchImpl(base + path, {
        method,
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: body === void 0 ? void 0 : JSON.stringify(body)
      });
      status = response.status;
      if (status === 429 || status >= 500) {
        const retryAfter = Number(response.headers?.get?.("retry-after") ?? 0);
        await wait(Math.min(2e3, Math.max(retryAfter * 1e3, 250 * 2 ** attempt)));
        continue;
      }
      const text = await response.text();
      const payload = text ? JSON.parse(text) : {};
      if (status < 200 || status >= 300) {
        throw new HubSpotApiError(status, method, path.split("?")[0], payload.category, payload.correlationId);
      }
      return payload;
    }
    throw new HubSpotApiError(status, method, path.split("?")[0], "still failing after retries");
  }
  const api = {
    request,
    get: (path) => request("GET", path),
    post: (path, body) => request("POST", path, body),
    patch: (path, body) => request("PATCH", path, body),
    put: (path, body) => request("PUT", path, body),
    // Associated record IDs (v4), following pages.
    async associated(fromType, id, toType) {
      const ids = [];
      let after = "";
      do {
        const page = await request("GET", `/crm/v4/objects/${fromType}/${id}/associations/${toType}?limit=500${after}`);
        for (const row of page.results ?? []) ids.push({ id: String(row.toObjectId), types: row.associationTypes ?? [] });
        const next = page.paging?.next?.after;
        after = next ? `&after=${next}` : "";
      } while (after);
      return ids;
    },
    // Associated IDs for many records in one call per hundred (v4 batch read): { fromId: [{ id, types }] }.
    async associatedBatch(fromType, ids, toType) {
      const out = Object.fromEntries(ids.map((id) => [String(id), []]));
      for (let i = 0; i < ids.length; i += 100) {
        const page = await request("POST", `/crm/v4/associations/${fromType}/${toType}/batch/read`, {
          inputs: ids.slice(i, i + 100).map((id) => ({ id: String(id) }))
        });
        for (const row of page.results ?? []) {
          out[String(row.from.id)] = (row.to ?? []).map((t) => ({ id: String(t.toObjectId), types: t.associationTypes ?? [] }));
        }
      }
      return out;
    },
    async batchRead(objectType, ids, properties) {
      const out = [];
      for (let i = 0; i < ids.length; i += 100) {
        const page = await request("POST", `/crm/v3/objects/${objectType}/batch/read`, {
          inputs: ids.slice(i, i + 100).map((id) => ({ id })),
          properties
        });
        out.push(...page.results ?? []);
      }
      return out;
    },
    // A custom object's type ID from its name ("recommendation" -> "2-123456").
    async customType(name) {
      const schemas = await request("GET", "/crm/v3/schemas");
      const schema = (schemas.results ?? []).find((s) => s.name === name);
      if (!schema) throw new Error(`custom object "${name}" is not defined in this portal`);
      return schema.objectTypeId;
    },
    async labelType(fromType, toType, label) {
      const labels = await request("GET", `/crm/v4/associations/${fromType}/${toType}/labels`);
      const match = (labels.results ?? []).find((l) => label ? l.label === label : !l.label);
      if (!match) throw new Error(`no association ${label ? `labelled "${label}"` : "type"} from ${fromType} to ${toType}`);
      return { associationCategory: match.category, associationTypeId: match.typeId };
    }
  };
  return api;
}

// shared/signature.js
var MAX_AGE_MS = 5 * 60 * 1e3;

// shared/endpoint.js
function secret(context, name) {
  return context?.secrets?.[name] || process.env[name] || void 0;
}
function appClient(context) {
  return client({ token: secret(context, "PRIVATE_APP_ACCESS_TOKEN") });
}
function respond(statusCode, body) {
  return { statusCode, body };
}

// shared/cases.js
var TRANSITIONS = {
  "Open triage": ["Evidence requested", "Second-level review", "Closed: no further action"],
  "Evidence requested": ["Second-level review", "Closed: no further action"],
  "Second-level review": ["Evidence requested", "Closed: no further action", "Closed: referred for a reporting decision"],
  "Closed: no further action": [],
  "Closed: referred for a reporting decision": []
};
var DECISIONS = {
  "Closed: no further action": "no_further_action",
  "Closed: referred for a reporting decision": "referred_for_reporting_decision"
};
function allowedNext(stage) {
  return TRANSITIONS[stage] ?? [];
}
function checkTransition(from, to, note) {
  if (!allowedNext(from).includes(to)) {
    return { ok: false, reason: `a case in "${from}" cannot move to "${to}"` };
  }
  if (!note || note.trim().length < 10) {
    return { ok: false, reason: "say why in at least ten characters; the note is the audit trail" };
  }
  return { ok: true, decision: DECISIONS[to] ?? null };
}
var HOUR = 3600 * 1e3;
function logEntry(existing, when, who, from, to, note) {
  const line = `${new Date(when).toISOString().slice(0, 16).replace("T", " ")} UTC \xB7 ${who}: ${from} \u2192 ${to}. ${note.trim()}`;
  return existing ? `${existing}
${line}` : line;
}

// functions/case_transition.js
async function main(context, { api = appClient(context), now = Date.now() } = {}) {
  const caseId = context.propertiesToSend?.hs_object_id ?? context.parameters?.caseId;
  const { toStage, note } = context.parameters ?? {};
  if (!caseId || !toStage) return respond(400, { ok: false, error: "needs a case and a target stage" });
  const caseType = await api.customType("investigation_case");
  const [record] = await api.batchRead(caseType, [caseId], ["hs_pipeline", "hs_pipeline_stage", "case_activity_log"]);
  if (!record) return respond(404, { ok: false, error: "case not found" });
  const pipelines = await api.get(`/crm/v3/pipelines/${caseType}`);
  const pipeline = pipelines.results.find((p) => p.id === record.properties.hs_pipeline);
  if (!pipeline) return respond(400, { ok: false, error: "the case is not in a known pipeline" });
  const current = pipeline.stages.find((s) => s.id === record.properties.hs_pipeline_stage);
  const target = pipeline.stages.find((s) => s.label === toStage);
  if (!current || !target) return respond(400, { ok: false, error: `unknown stage "${toStage}"` });
  const check = checkTransition(current.label, target.label, note);
  if (!check.ok) return respond(400, { ok: false, error: check.reason });
  const who = context.userEmail ?? context.parameters?.actor ?? `user ${context.userId ?? "unknown"}`;
  const properties = {
    hs_pipeline_stage: target.id,
    case_activity_log: logEntry(record.properties.case_activity_log, now, who, current.label, target.label, note)
  };
  if (check.decision) properties.decision_status = check.decision;
  await api.patch(`/crm/v3/objects/${caseType}/${caseId}`, { properties });
  return respond(200, { ok: true, from: current.label, to: target.label, decision: check.decision });
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  main
});
