"""Render docs/live-evidence.md from the evidence files the live runs wrote (``evidence/<tenant>/*.json``).

``python -m crm_platform.evidence`` rewrites the page; ``--check`` fails if it is stale. A test runs the check, so
the page can only say what the evidence files say.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "evidence"
DOC = ROOT / "docs" / "live-evidence.md"
NAMES = {"scalelab": "ScaleLab (GrowthOps OS)", "meridian": "Meridian Supply", "crosssell": "Meat distributor",
         "aml": "AML investigations"}


def _load(tenant: str, name: str) -> dict[str, Any] | None:
    path = EVIDENCE / tenant / f"{name}.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def _objects(report: dict[str, Any], kind: str) -> str:
    return ", ".join(f"{name} {counts[kind]:,}" for name, counts in report.items() if counts[kind]) or "none"


def _salesforce() -> list[str]:
    """The Meridian model and guardrail in a Salesforce Developer Edition org: the deploy, then the loads."""
    deploy = _load("meridian", "salesforce_deploy")
    first = _load("meridian", "salesforce_first_load")
    latest = _load("meridian", "salesforce_load")
    if not (deploy and first and latest):
        return []
    cover = [100 * c["covered"] / c["lines"] for c in deploy["coverage"].values()]
    tests = deploy["apexTests"]
    created = _objects(first["load"]["objects"], "create")
    entries = first["load"]["price_book"]["create"]
    left = {name: o["fields_changed"] for name, o in first["verify"]["objects"].items() if o["update"] or o["create"]}
    after = ("nothing left to do" if first["verify"]["converged"] else "left to do: "
             + "; ".join(f"{name} {', '.join(fields)}" for name, fields in left.items()))
    unchanged = sum(o["unchanged"] for o in latest["verify"]["objects"].values())
    return ["", "## Salesforce", "",
            (f"Meridian's model and guardrail in a {deploy['org']['organizationType']} org "
             f"(`{deploy['org']['orgId']}`), deployed and loaded from the runbook's commands."), "",
            "| What | Result |", "|---|---|",
            (f"| Deploy `{deploy['deployId']}`, {deploy['testLevel']} | {deploy['status']}: "
             f"{deploy['components']['deployed']} of {deploy['components']['total']} components, "
             f"{tests['run'] - tests['failed']} of {tests['run']} Apex tests, class coverage "
             f"{min(cover):.0f}% to {max(cover):.0f}% |"),
            (f"| First load ({first['at'][:10]}) | Created {created}, price-book entries {entries:,} in "
             f"{first['writes']} writes, {len(first['load']['failures'])} failures; planned again, {after} |"),
            (f"| Latest load ({latest['at'][:10]}) | {latest['writes']} writes; planned again, "
             f"{'converged' if latest['verify']['converged'] else 'not converged'}: {unchanged:,} records unchanged |"),
            "",
            ("The first load's leftover is the cross-system check doing its job: on one opportunity the Apex trigger "
             "and the loader rounded a blended margin of exactly 0.53125 differently. The loader's rounding was "
             "changed to match Apex and JavaScript, and the latest load is the rerun after that fix.")]


def render() -> str:
    lines = ["# Live evidence", "",
             "Generated by `python -m crm_platform.evidence` from `evidence/<tenant>/*.json`; do not edit.", "",
             ("Every portal is a HubSpot developer test account on Enterprise tiers, bound to one business "
              "(`evidence/<tenant>/deploy.json`). Counts and IDs only: the evidence files never hold record values."),
             "",
             "## Loads and convergence", "",
             "| Business | Portal | Created | Associations created | Verify: left to do | Verify writes |",
             "|---|---|---|---|---|---|"]
    for tenant in ("meridian", "crosssell", "aml", "scalelab"):
        apply = _load(tenant, "apply")
        if apply is None:
            continue
        first = _load(tenant, "first_load")
        objects = apply.get("load", {}).get("objects", {})
        links = apply.get("load", {}).get("links", {})
        if first:
            created = ", ".join(f"{k} {v:,}" for k, v in first["created"].items())
            associated = f"{sum(first['associations_created'].values()):,}"
        elif objects:
            created = _objects(objects, "create")
            associated = f"{sum(link['create'] for link in links.values()):,}"
        else:
            created, associated = "none (the app reads GrowthOps' own data)", "none"
        left = "nothing" if apply["verify"]["converged"] else "see the evidence file"
        lines.append(f"| {NAMES[tenant]} | {apply['portal']['portal_id']} | {created} | {associated} | {left} | "
                     f"{apply['verify']['writes']} |")
    aml = _load("aml", "apply")
    if aml:
        unchanged = sum(o["unchanged"] for o in aml["load"]["objects"].values())
        lines += ["", (f"The AML row's second run is the idempotency check against the real API: all {unchanged:,} "
                       "records came back unchanged and every association was already present, so it wrote nothing "
                       "but the two stage fixes it was rerun for.")]
    lines += _salesforce()
    webhook = _load("scalelab", "webhook_delivery")
    action = _load("scalelab", "workflow_action")
    if webhook or action:
        lines += ["", "## HubSpot calling the apps", "", "| What | Result |", "|---|---|"]
    if webhook:
        mon = webhook["hubspot_monitoring"]
        lines.append(f"| Signed webhook delivered by HubSpot ({mon['subscription_type']}) | {mon['result']}: "
                     f"verified and accepted; batch `{mon['batch_id']}` |")
    if action:
        lines.append(f"| Workflow \"{action['workflow']['name']}\" ran the custom action | "
                     f"{action['result']['lifecyclestage_before']} → {action['result']['lifecyclestage_after']} |")
        for call in action["hubspot_monitoring_2026-10-01_EDT"]["endpoint_functions"]:
            lines.append(f"| `{call['endpoint']}` at {call['time']} EDT | {call['result']}: {call['meaning']} |")
    accept = _load("crosssell", "idempotent_accept")
    if accept:
        deal = accept["deal"]
        linked = ", ".join(f"{k} {len(v)}" for k, v in accept["associations_read_back"].items())
        lines += ["", "## A unique key against duplicate deals", "",
                  (f"The cross-sell portal's deals carry `{accept['schema_change']['property']}`, unique, added in "
                   f"{accept['schema_change']['writes']} schema writes (verify afterwards: "
                   f"{accept['schema_change']['verify_writes_after']} writes). Accepting an offer from the card "
                   f"created deal {deal['id']} with key `{deal['crm_platform_key']}`, already linked ({linked}); "
                   f"the offer has {accept['deals_for_the_offer']} deal. A second create with the same key was then "
                   f"sent on purpose: HubSpot answered {accept['duplicate_probe']['answer']} and the offer still has "
                   f"{accept['duplicate_probe']['deals_with_the_key_after']} deal, so a racing request finds the "
                   "first one by its key and carries on with it.")]
    lines += ["", "## Cards on real records", "",
              "Each card was added to its object's record view and used on a loaded record:", "",
              "| Card | Record | What it showed |", "|---|---|---|",
              ("| Deal margin guardrail | Summit Distribution · May 2026 RFQ (won lines) | 2.9% blended margin, "
               "$2,030 under target, \"Below floor: VP Finance must approve\" |"),
              ("| Next best offer | Aurora Kaiseki 001 | Three eligible offers; \"Create deal\" made a $522.50 deal "
               "with the product as a line item and marked the offer accepted |"),
              ("| Case evidence | INV-ENT-00060 · Becky Horton | P0 deadline, layering hypothesis against its lawful "
               "lookalike, shared counterparties; a move to Evidence requested logged with its reason |"),
              ("| Revenue truth | A GrowthOps customer | $6,300 collected, the campaign each attribution model "
               "credits, products bought through the contact's deals, high renewal risk |"),
              ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not DOC.exists() or DOC.read_text(encoding="utf-8") != text:
            sys.exit("docs/live-evidence.md is stale: run python -m crm_platform.evidence")
        print("live evidence page is current")
        return
    DOC.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
