// Generated by build.mjs from hubspot/functions/company_offers.js and hubspot/shared. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/company_offers.js
var company_offers_exports = {};
__export(company_offers_exports, {
  OFFER_PROPERTIES: () => OFFER_PROPERTIES,
  main: () => main
});
module.exports = __toCommonJS(company_offers_exports);

// shared/hubspot-api.js
var HubSpotApiError = class extends Error {
  constructor(status, method, path, category = "", correlationId = "") {
    super(`HubSpot ${method} ${path} failed: HTTP ${status}${category ? ` ${category}` : ""}${correlationId ? ` (correlation ${correlationId})` : ""}`);
    this.status = status;
    this.category = category;
  }
};
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function client({
  token = process.env.PRIVATE_APP_ACCESS_TOKEN,
  fetchImpl = globalThis.fetch,
  wait = sleep,
  base = "https://api.hubapi.com"
} = {}) {
  if (!token) throw new Error("PRIVATE_APP_ACCESS_TOKEN is not available to this function");
  async function request(method, path, body) {
    let status = 0;
    for (let attempt = 0; attempt < 3; attempt += 1) {
      const response = await fetchImpl(base + path, {
        method,
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: body === void 0 ? void 0 : JSON.stringify(body)
      });
      status = response.status;
      if (status === 429 || status >= 500) {
        const retryAfter = Number(response.headers?.get?.("retry-after") ?? 0);
        await wait(Math.min(2e3, Math.max(retryAfter * 1e3, 250 * 2 ** attempt)));
        continue;
      }
      const text = await response.text();
      const payload = text ? JSON.parse(text) : {};
      if (status < 200 || status >= 300) {
        throw new HubSpotApiError(status, method, path.split("?")[0], payload.category, payload.correlationId);
      }
      return payload;
    }
    throw new HubSpotApiError(status, method, path.split("?")[0], "still failing after retries");
  }
  const api = {
    request,
    get: (path) => request("GET", path),
    post: (path, body) => request("POST", path, body),
    patch: (path, body) => request("PATCH", path, body),
    put: (path, body) => request("PUT", path, body),
    // Associated record IDs (v4), following pages.
    async associated(fromType, id, toType) {
      const ids = [];
      let after = "";
      do {
        const page = await request("GET", `/crm/v4/objects/${fromType}/${id}/associations/${toType}?limit=500${after}`);
        for (const row of page.results ?? []) ids.push({ id: String(row.toObjectId), types: row.associationTypes ?? [] });
        const next = page.paging?.next?.after;
        after = next ? `&after=${next}` : "";
      } while (after);
      return ids;
    },
    async batchRead(objectType, ids, properties) {
      const out = [];
      for (let i = 0; i < ids.length; i += 100) {
        const page = await request("POST", `/crm/v3/objects/${objectType}/batch/read`, {
          inputs: ids.slice(i, i + 100).map((id) => ({ id })),
          properties
        });
        out.push(...page.results ?? []);
      }
      return out;
    },
    // A custom object's type ID from its name ("recommendation" -> "2-123456").
    async customType(name) {
      const schemas = await request("GET", "/crm/v3/schemas");
      const schema = (schemas.results ?? []).find((s) => s.name === name);
      if (!schema) throw new Error(`custom object "${name}" is not defined in this portal`);
      return schema.objectTypeId;
    },
    async labelType(fromType, toType, label) {
      const labels = await request("GET", `/crm/v4/associations/${fromType}/${toType}/labels`);
      const match = (labels.results ?? []).find((l) => label ? l.label === label : !l.label);
      if (!match) throw new Error(`no association ${label ? `labelled "${label}"` : "type"} from ${fromType} to ${toType}`);
      return { associationCategory: match.category, associationTypeId: match.typeId };
    }
  };
  return api;
}

// functions/company_offers.js
var OFFER_PROPERTIES = [
  "offer_title",
  "offer_rank",
  "offer_score",
  "offer_sku",
  "offer_protein",
  "offer_revenue_opportunity",
  "offer_because",
  "offer_status",
  "offer_decided_at",
  "offer_decision_note"
];
var STATUS_ORDER = { open: 0, accepted: 1, dismissed: 2 };
async function main(context, { api = client() } = {}) {
  const companyId = context.propertiesToSend?.hs_object_id ?? context.parameters?.companyId;
  if (!companyId) return { ok: false, error: "no company in context" };
  const offerType = await api.customType("recommendation");
  const links = await api.associated("companies", companyId, offerType);
  const offers = await api.batchRead(offerType, links.map((l) => l.id), OFFER_PROPERTIES);
  const result = [];
  for (const offer of offers) {
    const p = offer.properties;
    const deals = p.offer_status === "accepted" ? await api.associated(offerType, offer.id, "deals") : [];
    result.push({
      id: offer.id,
      title: p.offer_title,
      rank: Number(p.offer_rank),
      sku: p.offer_sku,
      protein: p.offer_protein,
      opportunity: Number(p.offer_revenue_opportunity),
      because: p.offer_because,
      status: p.offer_status ?? "open",
      decidedAt: p.offer_decided_at ?? null,
      note: p.offer_decision_note ?? "",
      dealId: deals[0]?.id ?? null
    });
  }
  result.sort((a, b) => STATUS_ORDER[a.status] - STATUS_ORDER[b.status] || a.rank - b.rank);
  return { ok: true, offers: result };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  OFFER_PROPERTIES,
  main
});
