// Generated by build.mjs from hubspot/functions/decide_offer.js and hubspot/shared. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/decide_offer.js
var decide_offer_exports = {};
__export(decide_offer_exports, {
  main: () => main
});
module.exports = __toCommonJS(decide_offer_exports);

// shared/hubspot-api.js
var HubSpotApiError = class extends Error {
  constructor(status, method, path, category = "", correlationId = "") {
    super(`HubSpot ${method} ${path} failed: HTTP ${status}${category ? ` ${category}` : ""}${correlationId ? ` (correlation ${correlationId})` : ""}`);
    this.status = status;
    this.category = category;
  }
};
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
function client({
  token = process.env.PRIVATE_APP_ACCESS_TOKEN,
  fetchImpl = globalThis.fetch,
  wait = sleep,
  base = "https://api.hubapi.com"
} = {}) {
  if (!token) throw new Error("PRIVATE_APP_ACCESS_TOKEN is not available to this function");
  async function request(method, path, body) {
    let status = 0;
    for (let attempt = 0; attempt < 3; attempt += 1) {
      const response = await fetchImpl(base + path, {
        method,
        headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
        body: body === void 0 ? void 0 : JSON.stringify(body)
      });
      status = response.status;
      if (status === 429 || status >= 500) {
        const retryAfter = Number(response.headers?.get?.("retry-after") ?? 0);
        await wait(Math.min(2e3, Math.max(retryAfter * 1e3, 250 * 2 ** attempt)));
        continue;
      }
      const text = await response.text();
      const payload = text ? JSON.parse(text) : {};
      if (status < 200 || status >= 300) {
        throw new HubSpotApiError(status, method, path.split("?")[0], payload.category, payload.correlationId);
      }
      return payload;
    }
    throw new HubSpotApiError(status, method, path.split("?")[0], "still failing after retries");
  }
  const api = {
    request,
    get: (path) => request("GET", path),
    post: (path, body) => request("POST", path, body),
    patch: (path, body) => request("PATCH", path, body),
    put: (path, body) => request("PUT", path, body),
    // Associated record IDs (v4), following pages.
    async associated(fromType, id, toType) {
      const ids = [];
      let after = "";
      do {
        const page = await request("GET", `/crm/v4/objects/${fromType}/${id}/associations/${toType}?limit=500${after}`);
        for (const row of page.results ?? []) ids.push({ id: String(row.toObjectId), types: row.associationTypes ?? [] });
        const next = page.paging?.next?.after;
        after = next ? `&after=${next}` : "";
      } while (after);
      return ids;
    },
    async batchRead(objectType, ids, properties) {
      const out = [];
      for (let i = 0; i < ids.length; i += 100) {
        const page = await request("POST", `/crm/v3/objects/${objectType}/batch/read`, {
          inputs: ids.slice(i, i + 100).map((id) => ({ id })),
          properties
        });
        out.push(...page.results ?? []);
      }
      return out;
    },
    // A custom object's type ID from its name ("recommendation" -> "2-123456").
    async customType(name) {
      const schemas = await request("GET", "/crm/v3/schemas");
      const schema = (schemas.results ?? []).find((s) => s.name === name);
      if (!schema) throw new Error(`custom object "${name}" is not defined in this portal`);
      return schema.objectTypeId;
    },
    async labelType(fromType, toType, label) {
      const labels = await request("GET", `/crm/v4/associations/${fromType}/${toType}/labels`);
      const match = (labels.results ?? []).find((l) => label ? l.label === label : !l.label);
      if (!match) throw new Error(`no association ${label ? `labelled "${label}"` : "type"} from ${fromType} to ${toType}`);
      return { associationCategory: match.category, associationTypeId: match.typeId };
    }
  };
  return api;
}

// functions/decide_offer.js
async function ensureDeal(api, offerType, offerId, offer, company) {
  const existing = await api.associated(offerType, offerId, "deals");
  if (existing.length) return { dealId: existing[0].id, resumed: true };
  const products = await api.post("/crm/v3/objects/products/search", {
    filterGroups: [{ filters: [{ propertyName: "hs_sku", operator: "EQ", value: offer.offer_sku }] }],
    properties: ["name", "price"],
    limit: 1
  });
  const product = products.results?.[0];
  if (!product) throw new Error(`no product with SKU ${offer.offer_sku}`);
  const price = Number(product.properties.price);
  const quantity = Math.max(1, Math.round(Number(offer.offer_revenue_opportunity) / price));
  const pipelines = await api.get("/crm/v3/pipelines/deals");
  const pipeline = pipelines.results.find((p) => p.id === "default") ?? pipelines.results[0];
  const stage = [...pipeline.stages].sort((a, b) => a.displayOrder - b.displayOrder)[0];
  const deal = await api.post("/crm/v3/objects/deals", { properties: {
    dealname: `${company.name} \xB7 ${product.properties.name} (cross-sell)`,
    amount: (quantity * price).toFixed(2),
    pipeline: pipeline.id,
    dealstage: stage.id
  } });
  const converted = await api.labelType(offerType, "deals", "Converted to deal");
  await api.put(`/crm/v4/objects/${offerType}/${offerId}/associations/deals/${deal.id}`, [converted]);
  return { dealId: deal.id, resumed: false, product, quantity, price };
}
async function ensureLineItem(api, dealId, sku) {
  if ((await api.associated("deals", dealId, "line_items")).length) return;
  const products = await api.post("/crm/v3/objects/products/search", {
    filterGroups: [{ filters: [{ propertyName: "hs_sku", operator: "EQ", value: sku }] }],
    properties: ["name", "price"],
    limit: 1
  });
  const product = products.results[0];
  const [deal] = await api.batchRead("deals", [dealId], ["amount"]);
  const price = Number(product.properties.price);
  const quantity = Math.max(1, Math.round(Number(deal.properties.amount) / price));
  const line = await api.post("/crm/v3/objects/line_items", { properties: {
    hs_product_id: product.id,
    quantity: String(quantity),
    price: price.toFixed(2),
    name: product.properties.name
  } });
  await api.put(
    `/crm/v4/objects/line_items/${line.id}/associations/deals/${dealId}`,
    [await api.labelType("line_items", "deals", null)]
  );
}
async function main(context, { api = client(), now = Date.now() } = {}) {
  const { offerId, decision, note = "" } = context.parameters ?? {};
  const who = context.userEmail ?? `user ${context.userId ?? "unknown"}`;
  if (!offerId || !["accept", "dismiss"].includes(decision)) return { ok: false, error: "needs offerId and decision" };
  if (decision === "dismiss" && note.trim().length < 5) return { ok: false, error: "say why the offer is dismissed" };
  const offerType = await api.customType("recommendation");
  const [record] = await api.batchRead(offerType, [offerId], [
    "offer_title",
    "offer_sku",
    "offer_status",
    "offer_revenue_opportunity"
  ]);
  if (!record) return { ok: false, error: "offer not found" };
  const offer = record.properties;
  const decided = {
    offer_decided_at: new Date(now).toISOString(),
    offer_decision_note: `${who}: ${note.trim() || "accepted"}`.slice(0, 1e3)
  };
  if (decision === "dismiss") {
    if (offer.offer_status !== "open") return { ok: false, error: `offer is already ${offer.offer_status}` };
    await api.patch(`/crm/v3/objects/${offerType}/${offerId}`, { properties: { offer_status: "dismissed", ...decided } });
    return { ok: true, dismissed: true };
  }
  if (offer.offer_status === "dismissed") return { ok: false, error: "offer was dismissed" };
  const [companyLink] = await api.associated(offerType, offerId, "companies");
  if (!companyLink) return { ok: false, error: "offer has no company" };
  const [company] = await api.batchRead("companies", [companyLink.id], ["name"]);
  const deal = await ensureDeal(api, offerType, offerId, offer, { id: company.id, name: company.properties.name });
  await api.put(
    `/crm/v4/objects/deals/${deal.dealId}/associations/companies/${company.id}`,
    [await api.labelType("deals", "companies", null)]
  );
  const buyers = await api.associated("companies", company.id, "contacts");
  if (buyers.length) {
    await api.put(
      `/crm/v4/objects/deals/${deal.dealId}/associations/contacts/${buyers[0].id}`,
      [await api.labelType("deals", "contacts", null)]
    );
  }
  await ensureLineItem(api, deal.dealId, offer.offer_sku);
  if (offer.offer_status !== "accepted") {
    await api.patch(`/crm/v3/objects/${offerType}/${offerId}`, { properties: { offer_status: "accepted", ...decided } });
  }
  return { ok: true, dealId: deal.dealId, resumed: deal.resumed };
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  main
});
