// Generated by build.mjs from hubspot/functions/provision.js and hubspot/shared. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// functions/provision.js
var provision_exports = {};
__export(provision_exports, {
  ALLOWED: () => ALLOWED,
  MAX_AGE_MS: () => MAX_AGE_MS2,
  PATH: () => PATH,
  allowed: () => allowed,
  main: () => main,
  signRequest: () => signRequest
});
module.exports = __toCommonJS(provision_exports);
var import_node_crypto = require("node:crypto");

// shared/signature.js
var MAX_AGE_MS = 5 * 60 * 1e3;
function header(headers, name) {
  const wanted = name.toLowerCase();
  for (const [key, value] of Object.entries(headers ?? {})) {
    if (key.toLowerCase() === wanted) return Array.isArray(value) ? value[0] : value;
  }
  return void 0;
}

// shared/endpoint.js
function secret(context, name) {
  return context?.secrets?.[name] || process.env[name] || void 0;
}
function parsedBody(context) {
  const body = context.body;
  if (typeof body === "string") return body ? JSON.parse(body) : {};
  return body ?? {};
}
function respond(statusCode, body) {
  return { statusCode, body };
}

// functions/provision.js
var PATH = "/hs/serverless/provision";
var MAX_AGE_MS2 = 5 * 60 * 1e3;
var T = "[0-9]+-[0-9]+|[a-z_]+";
var ALLOWED = [
  ["GET", new RegExp(`^/account-info/v3/details$`)],
  ["GET", new RegExp(`^/crm/v3/schemas$`)],
  ["POST", new RegExp(`^/crm/v3/schemas$`)],
  ["POST", new RegExp(`^/crm/v3/schemas/(${T})/associations$`)],
  ["GET", new RegExp(`^/crm/v3/properties/(${T})(/groups)?$`)],
  ["POST", new RegExp(`^/crm/v3/properties/(${T})/(groups|batch/create)$`)],
  ["PATCH", new RegExp(`^/crm/v3/properties/(${T})/[a-z0-9_]+$`)],
  ["GET", new RegExp(`^/crm/v3/pipelines/(${T})$`)],
  ["POST", new RegExp(`^/crm/v3/pipelines/(${T})(/[A-Za-z0-9_-]+/stages)?$`)],
  ["PATCH", new RegExp(`^/crm/v3/pipelines/(${T})/[A-Za-z0-9_-]+/stages/[A-Za-z0-9_-]+$`)],
  ["GET", new RegExp(`^/crm/v4/associations/(${T})/(${T})/labels$`)],
  ["POST", new RegExp(`^/crm/v4/associations/(${T})/(${T})/(labels|batch/read|batch/create)$`)],
  ["GET", new RegExp(`^/crm/v3/objects/(${T})$`)],
  ["POST", new RegExp(`^/crm/v3/objects/(${T})/batch/(read|create|update)$`)]
];
function allowed(method, path) {
  const route = path.split("?")[0];
  return ALLOWED.some(([m, pattern]) => m === method && pattern.test(route));
}
function signRequest(key, timestamp, method, path, body) {
  return (0, import_node_crypto.createHmac)("sha256", key).update(`${timestamp}.${method}.${path}.${body}`).digest("hex");
}
function verified(key, context, request, now) {
  const timestamp = Number(header(context.headers, "x-crm-platform-timestamp"));
  const given = String(header(context.headers, "x-crm-platform-signature") ?? "");
  if (!key) return "no provision key configured";
  if (!Number.isFinite(timestamp) || Math.abs(now - timestamp) > MAX_AGE_MS2) return "stale or missing timestamp";
  const expected = signRequest(key, timestamp, request.method, request.path, request.bodyText ?? "");
  const a = Buffer.from(expected);
  const b = Buffer.from(given);
  return a.length === b.length && (0, import_node_crypto.timingSafeEqual)(a, b) ? null : "signature mismatch";
}
async function main(context, { now = Date.now(), fetchImpl = globalThis.fetch, key, token } = {}) {
  const request = parsedBody(context);
  const problem = verified(key ?? secret(context, "PROVISION_KEY"), context, request, now);
  if (problem) return respond(401, { error: problem });
  if (!allowed(request.method, request.path ?? "")) {
    return respond(403, { error: `not allowed: ${request.method} ${String(request.path).split("?")[0]}` });
  }
  const appToken = token ?? secret(context, "PRIVATE_APP_ACCESS_TOKEN");
  const upstream = await fetchImpl(`https://api.hubapi.com${request.path}`, {
    method: request.method,
    headers: { Authorization: `Bearer ${appToken}`, "Content-Type": "application/json" },
    body: request.bodyText ? request.bodyText : void 0
  });
  const text = await upstream.text();
  const headers = {};
  for (const name of ["retry-after", "x-hubspot-ratelimit-daily-remaining", "x-hubspot-ratelimit-remaining"]) {
    const value = upstream.headers?.get?.(name);
    if (value) headers[name] = value;
  }
  let body = null;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    body = null;
  }
  return respond(200, { status: upstream.status, headers, body });
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  ALLOWED,
  MAX_AGE_MS,
  PATH,
  allowed,
  main,
  signRequest
});
